# Bin.Li@EXP.BSP.bootloader.bootflow, 2017/05/15, Add for oppo device info and oppo project
#obj-$(CONFIG_OPPO_COMMON_SOFT)  +=  oppo_project/
obj-$(CONFIG_OPPO_DEVICE_IFNO)  +=  oppo_devinfo/

#obj-y += oppo_custom/
#obj-$(CONFIG_OPPO_HYPNUS)       +=  oppo_hypnus/

